apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
data:
  master.cnf: |
    # 主节点Mysql的配置文件
    [mysqld]
    log-bin
    explicit_defaults_for_timestamp=true
  slave.cnf: |
    # 从节点Mysql的配置文件
    [mysqld]
    super-read-only
    explicit_defaults_for_timestamp=true